### ISSUE TITLE
Trouble with parameters' setting

### ISSUE THREAD

**Issue by HerbalCookie** [bioinfoguru/molecular_docking#1]
Hello there! So glad to find this app, @bioinfoguru , thanks a lot for your work. Unfortunately, I stuck in the step "Enter docking parameters; for details about these please refer to the ADFR manual". I totally confused with that, as I could not find any manual for ADFR, just some tutorials in Documentation which are made for linux users, I suppose... Could you tell me, what should I consider to place in the "Command line parameters" gap, please? Thanks in advance.

**Comment by bioinfoguru** [comment]
Hi, thanks for your message. The adfr program offers various options to customize  the docking run. Some of these options can be set using this app. The command line parameters field allows user to enter additional command-line options, if required. For full list of options, run adfr.bat -h on the command prompt. The adfr.bat file is in the bin folder of the adfr program. 
Hope this helps.

**Comment by HerbalCookie** [comment]
Got it, thank you. There appeared another difficulty - when I launch the app, command prompt shows only 
"Reading C:/PDBs/dockingprocess/5xds_target_config.ini... Running ADFR
Done"
And nothing happens then... I thought this could be due to the time needed for data processing, however nothing changes in a while. Tried to do it 3 times. :D
What would you recommend me to do to manage the launch properly? Maybe I am missing something?

![image](https://github.com/bioinfoguru/molecular_docking/assets/143966033/7fcc71a4-9374-4f2b-9a7a-9aeaca14dd08)

**Comment by bioinfoguru** [comment]
Could you please check if there is any log/output file in the output path folder? Hope you clicked generate config before running ADFR. 
Also, please open the config.ini file in a text editor and see if everything looks ok.

**Comment by HerbalCookie** [comment]
There are no such files, unfortunately. Yes, I did generated config before launching, file .ini appeared right after clicking "Generate config", it seems to be fine
![image](https://github.com/bioinfoguru/molecular_docking/assets/143966033/16c3702f-de8e-40ba-8ff6-f9d21151e882)

**Comment by bioinfoguru** [comment]
In the Ligand pdbqt field, please select the folder having pdbqt file(s) and not a pdbqt file. Kindly make this change and run again.

**Comment by HerbalCookie** [comment]
This works! Thanks a lot for your help and patience!

**Comment by bioinfoguru** [comment]
Glad that you are now able to run the calculations. Please do not hesitate to contact should you need any additional help.
